import React, { forwardRef } from 'react';
import { Activity, Zap } from 'lucide-react';

interface ShareCardProps {
  speed: number;
  formScore: number;
  kickType: string;
}

export const ShareCard = forwardRef<HTMLDivElement, ShareCardProps>(
  ({ speed, formScore, kickType }, ref) => {
    return (
      <div 
        ref={ref}
        className="w-[400px] h-[600px] bg-black text-white p-8 relative overflow-hidden font-sans border-4 border-[#39ff14] flex flex-col justify-between"
        style={{
          background: 'linear-gradient(135deg, #000000 0%, #1a1a1a 100%)',
          boxSizing: 'border-box'
        }}
      >
        {/* Neon Accents */}
        <div className="absolute -top-20 -right-20 w-64 h-64 bg-[#39ff14] opacity-20 blur-[100px] rounded-full" style={{ filter: 'blur(100px)' }}></div>
        <div className="absolute -bottom-20 -left-20 w-64 h-64 bg-[#00f3ff] opacity-20 blur-[100px] rounded-full" style={{ filter: 'blur(100px)' }}></div>

        {/* Header */}
        <div className="flex flex-col gap-2 relative z-10 border-b border-white/20 pb-4">
          <h1 className="text-3xl font-black italic tracking-tighter text-[#39ff14]">
            FREEKICK MASTER
          </h1>
          <div className="text-sm font-mono text-gray-400 uppercase tracking-widest flex items-center gap-2">
            <Activity size={14} className="text-[#00f3ff]" /> AI Analysis Result
          </div>
        </div>

        {/* Main Stats */}
        <div className="flex-1 flex flex-col justify-center items-center gap-10 relative z-10">
          <div className="flex flex-col items-center">
            <div className="text-gray-400 font-mono text-sm tracking-widest mb-1">BALL SPEED</div>
            <div className="text-7xl font-black text-white flex items-baseline gap-2" style={{ textShadow: '0 0 15px rgba(57,255,20,0.5)' }}>
              {speed} <span className="text-2xl text-[#39ff14]" style={{ textShadow: 'none' }}>km/h</span>
            </div>
          </div>
          
          <div className="flex flex-col items-center">
            <div className="text-gray-400 font-mono text-sm tracking-widest mb-1">FORM SCORE</div>
            <div className="text-7xl font-black text-white flex items-baseline gap-2" style={{ textShadow: '0 0 15px rgba(0,243,255,0.5)' }}>
              {formScore} <span className="text-2xl text-[#00f3ff]" style={{ textShadow: 'none' }}>pts</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-between items-end relative z-10 pt-4 border-t border-white/20">
          <div className="flex flex-col">
            <div className="text-xs text-gray-500 font-mono uppercase">Kick Type</div>
            <div className="text-lg font-bold text-white flex items-center gap-1">
              <Zap size={16} className="text-yellow-400" />
              {kickType}
            </div>
          </div>
          <div className="text-xs font-mono text-gray-500 text-right">
            Generated by<br/>
            <span className="text-white font-bold tracking-widest">SHOOTING-LIKE</span>
          </div>
        </div>
      </div>
    );
  }
);

ShareCard.displayName = 'ShareCard';
